# Generated by Django 3.2 on 2021-06-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210607_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicator',
            name='prueba_horario',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='prueba_horario',
            field=models.DateTimeField(null=True),
        ),
    ]
