# Generated by Django 3.2 on 2021-06-15 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20210614_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaDeSalida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('fecha_de_salida', models.DateField(verbose_name='Fecha de Salida')),
            ],
            options={
                'verbose_name': 'Fecha de Salida',
                'verbose_name_plural': 'Fechas de Salidas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFechaDeSalida',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('fecha_de_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fecha de Salida',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHoraDeSalida',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('hora_de_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Hora de Salida',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNumeroDeBus',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('numero_de_bus', models.CharField(db_index=True, max_length=10, verbose_name='Numero De Bus')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Numero de Bus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTipoDeBus',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('tipo', models.CharField(db_index=True, max_length=50, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo de Bus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HoraDeSalida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('hora_de_salida', models.TimeField(verbose_name='Hora de Salida')),
            ],
            options={
                'verbose_name': 'Hora de Salida',
                'verbose_name_plural': 'Horas de Salidas',
            },
        ),
        migrations.CreateModel(
            name='NumeroDeBus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('numero_de_bus', models.CharField(max_length=10, unique=True, verbose_name='Numero De Bus')),
            ],
            options={
                'verbose_name': 'Numero de Bus',
                'verbose_name_plural': 'Numeros de Buses',
            },
        ),
        migrations.CreateModel(
            name='TipoDeBus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('tipo', models.CharField(max_length=50, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Tipo de Bus',
                'verbose_name_plural': 'Tipos de Buses',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('estado', models.BooleanField(null=True, verbose_name='Estado del Bus')),
                ('precio', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.RenameModel(
            old_name='HistoricalCategoryProduct',
            new_name='HistoricalDepartamento',
        ),
        migrations.RenameModel(
            old_name='HistoricalMeasureUnit',
            new_name='HistoricalDepartamento1',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='measure_unit',
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='departamento1',
            options={'verbose_name': 'Departamento1', 'verbose_name_plural': 'Departamentos1'},
        ),
        migrations.AlterModelOptions(
            name='historicaldepartamento',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Departamento'},
        ),
        migrations.AlterModelOptions(
            name='historicaldepartamento1',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Departamento1'},
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='description',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='departamento1',
            old_name='description',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='historicaldepartamento',
            old_name='description',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='historicaldepartamento1',
            old_name='description',
            new_name='departamento',
        ),
        migrations.RenameModel(
            old_name='MeasureUnit',
            new_name='Departamento',
        ),
        migrations.RenameModel(
            old_name='CategoryProduct',
            new_name='Departamento1',
        ),
        migrations.DeleteModel(
            name='HistoricalIndicator',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.departamento1', verbose_name='Departamento1'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_de_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.fechadesalida', verbose_name='Fecha de Salida'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_de_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.horadesalida', verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='numero_de_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.numerodebus', verbose_name='Numero de Bus'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='tipo_de_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tipodebus', verbose_name='Tipo de Bus'),
        ),
    ]
