# Generated by Django 3.2 on 2021-06-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210615_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='name',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre Del Viaje'),
        ),
    ]
